/**
 * Plain types only (no Firebase Admin imports) — same convention as
 * memberLifecycleTypes.ts, so both server modules and client components
 * can import from here safely.
 */

/**
 * `active`: a real, redeemable discount for this member/event pair.
 * `pending_external`: the Firestore record exists (so this member/event
 * pair is already claimed and can never double-grant) but the Ticket
 * Tailor discount hasn't been created yet — transient, or a create call
 * that failed and is awaiting retry.
 * `external_sync_failed`: a Ticket Tailor create call failed after at
 * least one attempt — distinct from `pending_external` only for
 * observability (how long has this actually been stuck vs. never tried).
 * `invalidated`: the member's entitlement ended before this event took
 * place (see invalidateUpcomingEventBenefitsForMember).
 *
 * Deliberately no `used`/`redeemed` status — Ticket Tailor's redemption
 * state was not verified as reliable enough to surface (see the Ticket
 * Tailor API audit). Never infer or fabricate a used state. There is also
 * no `superseded` status in this event-keyed model — nothing supersedes a
 * per-event benefit the way one billing cycle used to supersede the last;
 * a benefit is simply used, expired, or invalidated.
 */
export type EventBenefitStatus = "pending_external" | "active" | "external_sync_failed" | "invalidated";

export type EventBenefitInvalidationReason = "membership_lapsed" | null;

/**
 * `eventBenefits/{uid}_{ticketTailorEventId}` — one record per (member,
 * eligible event) pair, EVER, for the lifetime of that pair — the doc ID
 * itself is the idempotency key (see lifecycle.ts), which is what makes
 * "the same member gets two benefits for the same event" structurally
 * impossible, the same way the old `{subscriptionId}:{periodIndex}` key
 * made double-granting a billing cycle impossible. Deliberately keyed on
 * `uid`, not `stripeSubscriptionId` — a member who cancels and resubscribes
 * must never be granted a second benefit for an event they already got one
 * for the first time around.
 */
export interface EventBenefitDocument {
  uid: string;
  /** Also embedded in the doc ID — kept as its own field so `eventBenefits` can be queried/counted by event without parsing the ID. */
  ticketTailorEventId: string;
  /** The subscription active at grant time — audit/display only, never part of the key. */
  stripeSubscriptionId: string | null;
  createdAt: unknown; // Firestore Timestamp
  /** This event's own expiry boundary (end-of-day Madrid-local on the event's date) — see eligibility.ts. */
  validUntil: unknown; // Firestore Timestamp
  percentage: 20;
  /** Null until the Ticket Tailor create call actually succeeds. */
  ticketTailorDiscountId: string | null;
  /** The redeemable code shown to the member — generated by Junto, see codeGeneration.ts. */
  code: string;
  status: EventBenefitStatus;
  invalidatedAt: unknown | null; // Firestore Timestamp
  invalidatedReason: EventBenefitInvalidationReason;
}

/**
 * The narrow, per-event shape returned to the member — see
 * listEventBenefitsForMember. Deliberately never includes
 * ticketTailorDiscountId (internal bookkeeping) or another member's
 * record (every query is uid-scoped server-side, and Firestore rules
 * independently enforce the same boundary for defense in depth).
 * `code`/`validUntil` are `null` while `ready` is `false` — the member
 * never sees a code that isn't confirmed live yet.
 */
export interface MemberEventBenefitView {
  ticketTailorEventId: string;
  eventLabel: string;
  eventDate: string | null;
  checkoutUrl: string | null;
  ready: boolean;
  code: string | null;
  percentage: number;
  validUntil: unknown | null;
}

/**
 * The per-event row shown on the admin member-detail page — see
 * listEventBenefitsForAdmin. Unlike MemberEventBenefitView, this is never
 * filtered (invalidated benefits are shown too, so Lara can see "expired/
 * invalidated" as its own state) and always includes the real code and
 * status, since this is an admin-only, already-authenticated view.
 */
export interface AdminEventBenefitView {
  ticketTailorEventId: string;
  eventLabel: string;
  eventDate: string | null;
  status: EventBenefitStatus;
  code: string;
  validUntil: unknown;
  invalidatedReason: EventBenefitInvalidationReason;
}

/**
 * `eligibleTicketTailorEvents/{ticketTailorEventId}` — Junto's own,
 * explicit record of which Ticket Tailor events/ticket types participate
 * in the member benefit. Deliberately NOT inferred from any Ticket
 * Tailor-side tag/category/name — the Ticket Tailor API audit found no
 * supported native mechanism for this, so Junto is the source of truth
 * for eligibility, same as it already is for membership entitlement.
 * Admin-managed only (see eligibleEvents.ts) — no legitimate client read
 * or write path, same treatment as `matchingCycles`/`legacyImports`.
 */
export interface EligibleTicketTailorEventDocument {
  ticketTailorEventId: string;
  ticketTailorTicketTypeIds: string[];
  label: string;
  createdAt: unknown; // Firestore Timestamp
  updatedAt: unknown; // Firestore Timestamp
  /** Bookkeeping only — when a sync last ran and what it found, for admin visibility/debugging. */
  lastSyncedAt: unknown | null;
  lastSyncResult: { checked: number; granted: number; errors: number } | null;
  /**
   * Reconnect (see src/lib/eventReconnect/) extends this SAME document
   * rather than a second event registry — both features key off the same
   * Ticket Tailor event identity, and Lara already visits this one admin
   * screen once per event. `eventDate` is the calendar date Ticket Tailor
   * lists for the event (YYYY-MM-DD, Madrid-local) — Reconnect's open/close
   * window is always COMPUTED from it (see eventConfig.ts), never stored
   * separately, so these two timestamps can never drift from the event
   * date. The 20% benefit ALSO derives both eligibility and expiry from
   * this same field (see eligibility.ts) — required whenever
   * `memberBenefitEnabled` is true (see the eligible-events route's
   * validation), even though the type keeps it nullable for a
   * Reconnect-only or not-yet-dated registration. `reconnectEnabled`
   * defaults to `false`: registering an event for the discount benefit
   * must never implicitly turn on Reconnect for it too. `reconnectForceClosedAt`
   * is the one manual safety override (see the audit) — set, it closes
   * discovery immediately regardless of the computed window; independent
   * of `reconnectEnabled` so Lara can force-close without un-registering
   * the event.
   */
  eventDate: string | null;
  reconnectEnabled: boolean;
  reconnectForceClosedAt: unknown | null;
  /**
   * Whether this event participates in the member 20% benefit — fully
   * independent of `reconnectEnabled` (an event can be either, both, or
   * neither). `ticketTailorTicketTypeIds` and `eventDate` are only
   * required (see the eligible-events route's validation) when this is
   * `true`; both are irrelevant for a Reconnect-only event.
   *
   * BACKWARD COMPATIBILITY: this field did not exist before this toggle
   * was added, when every registered event implicitly participated in the
   * benefit. A document written before this field existed has it
   * `undefined`, not `false` — read paths treat "missing" the same as
   * `true` (only an EXPLICIT `false` excludes it). New/edited
   * registrations always write an explicit boolean (see the admin form's
   * own default).
   */
  memberBenefitEnabled: boolean;
  /**
   * The real Ticket Tailor purchase page for this event — the ONLY thing
   * that lets the member-facing "Comprar entrada con -20%" CTA link
   * anywhere real (see PlanSection.tsx's EventBenefitSection). `null`
   * until Lara fills it in; the CTA simply doesn't render without it — the
   * code and discount are still fully valid either way, this only affects
   * whether there's a one-click link to it.
   */
  ticketTailorCheckoutUrl: string | null;
}
