/**
 * Plain types only (no Firebase Admin imports) — same convention as
 * memberLifecycleTypes.ts, so both server modules and client components
 * can import from here safely.
 */

/**
 * `active`: the current, redeemable monthly benefit — at most ONE per
 * uid at any time (enforced by lifecycle.ts, never by a client).
 * `pending_external`: the Firestore record exists (so the cycle key is
 * already claimed and can never double-grant) but the Ticket Tailor
 * discount hasn't been created yet — a transient state, or the result of
 * a Ticket Tailor create call that failed and is awaiting retry.
 * `external_sync_failed`: a Ticket Tailor create/associate call failed
 * after at least one attempt — distinct from `pending_external` only for
 * observability (how long has this actually been stuck vs. never tried).
 * `superseded`: a later monthly cycle replaced this one (expected,
 * routine end of life).
 * `invalidated`: membership entitlement ended before the next monthly
 * cycle would have superseded this one naturally.
 *
 * Deliberately no `used` status in V1 — Ticket Tailor's redemption state
 * was not verified as reliable enough to surface (see the Ticket Tailor
 * API audit). Never infer or fabricate a used state.
 */
export type EventBenefitStatus = "pending_external" | "active" | "external_sync_failed" | "superseded" | "invalidated";

export type EventBenefitInvalidationReason = "superseded" | "membership_lapsed" | null;

/**
 * `eventBenefits/{cycleKey}` — one immutable-once-settled record per
 * monthly benefit cycle, never overwritten with a different cycle's data
 * (see lifecycle.ts's doc comment for why the doc ID IS the idempotency
 * key). Deliberately a dedicated collection, not a mutable array on
 * `profiles/{uid}` or `billing/{uid}` — mirrors the `introductions`/
 * `proposals` precedent: one doc per event, owner-uid field for the
 * Firestore rule, natural audit trail via a query on `uid`.
 */
export interface EventBenefitDocument {
  uid: string;
  stripeCustomerId: string | null;
  stripeSubscriptionId: string;
  /** `{stripeSubscriptionId}:{periodIndex}` — see anchor.ts. Also this doc's own Firestore id. */
  cycleKey: string;
  /** 0-indexed count of monthly cycles granted so far for this subscription. */
  periodIndex: number;
  createdAt: unknown; // Firestore Timestamp
  validFrom: unknown; // Firestore Timestamp — this cycle's own due date
  validUntil: unknown; // Firestore Timestamp — the next cycle's due date (when this one is naturally superseded)
  percentage: 20;
  /** Null until the Ticket Tailor create call actually succeeds. */
  ticketTailorDiscountId: string | null;
  /** The redeemable code shown to the member — generated by Junto, see codeGeneration.ts. */
  code: string;
  status: EventBenefitStatus;
  invalidatedAt: unknown | null; // Firestore Timestamp
  invalidatedReason: EventBenefitInvalidationReason;
}

/** The narrow shape actually returned to the member — see getCurrentEventBenefitForMember. */
export interface MemberEventBenefitView {
  code: string;
  percentage: number;
  validUntil: unknown;
}

/**
 * `eligibleTicketTailorEvents/{ticketTailorEventId}` — Junto's own,
 * explicit record of which Ticket Tailor events/ticket types participate
 * in the member benefit. Deliberately NOT inferred from any Ticket
 * Tailor-side tag/category/name — the Ticket Tailor API audit found no
 * supported native mechanism for this, so Junto is the source of truth
 * for eligibility, same as it already is for membership entitlement.
 * Admin-managed only (see eligibleEvents.ts) — no legitimate client read
 * or write path, same treatment as `matchingCycles`/`legacyImports`.
 */
export interface EligibleTicketTailorEventDocument {
  ticketTailorEventId: string;
  ticketTailorTicketTypeIds: string[];
  label: string;
  createdAt: unknown; // Firestore Timestamp
  updatedAt: unknown; // Firestore Timestamp
  /** Bookkeeping only — when a sync last ran and what it found, for admin visibility/debugging. */
  lastSyncedAt: unknown | null;
  lastSyncResult: { attempted: number; succeeded: number; failed: number } | null;
  /**
   * Reconnect (see src/lib/eventReconnect/) extends this SAME document
   * rather than a second event registry — both features key off the same
   * Ticket Tailor event identity, and Lara already visits this one admin
   * screen once per event. `eventDate` is the calendar date Ticket Tailor
   * lists for the event (YYYY-MM-DD, Madrid-local) — Reconnect's open/close
   * window is always COMPUTED from it (see eventConfig.ts), never stored
   * separately, so these two timestamps can never drift from the event
   * date. `null` for an event that predates Reconnect or was never given a
   * date — Reconnect is simply unavailable for it. `reconnectEnabled`
   * defaults to `false`: registering an event for the discount benefit
   * must never implicitly turn on Reconnect for it too. `reconnectForceClosedAt`
   * is the one manual safety override (see the audit) — set, it closes
   * discovery immediately regardless of the computed window; independent
   * of `reconnectEnabled` so Lara can force-close without un-registering
   * the event.
   */
  eventDate: string | null;
  reconnectEnabled: boolean;
  reconnectForceClosedAt: unknown | null;
  /**
   * Whether this event participates in the member 20% benefit — fully
   * independent of `reconnectEnabled` (an event can be either, both, or
   * neither). `ticketTailorTicketTypeIds` is only required (see the
   * eligible-events route's validation) when this is `true`; it's `false`
   * for a Reconnect-only event so `getAllEligibleTicketTypeIds()` never
   * pulls that event's ticket types into the benefit's union.
   *
   * BACKWARD COMPATIBILITY: this field did not exist before this toggle
   * was added, when every registered event implicitly participated in the
   * benefit (that was the only thing this document was for). A document
   * written before this field existed has it `undefined`, not `false` —
   * `getAllEligibleTicketTypeIds()` deliberately treats "missing" the same
   * as `true` (only an EXPLICIT `false` excludes it), so an already-active
   * member benefit tied to a pre-existing event is never silently broken
   * by this schema addition. New/edited registrations always write an
   * explicit boolean (see the admin form's own default).
   */
  memberBenefitEnabled: boolean;
}
